name: Continuous Integration

on:
  push:
    branches:
      - main
      - beta

  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "lts/*"

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          npm ci
          npx semantic-release
